plugins:
  - rubocop-rails
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'

# スタイル設定
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# メトリクス設定
Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'db/migrate/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'

Metrics/ParameterLists:
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'

Minitest/MultipleAssertions:
  Max: 10

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

# Rails設定
Rails/I18nLocaleTexts:
  Enabled: false
